/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html","./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      keyframes: {
        glitch: {
          '0%': { 'clip-path': 'inset(20% 0 50% 0)' },
          '5%': { 'clip-path': 'inset(10% 0 60% 0)' },
          '10%': { 'clip-path': 'inset(15% 0 55% 0)' },
          '15%': { 'clip-path': 'inset(25% 0 35% 0)' },
          '20%': { 'clip-path': 'inset(30% 0 40% 0)' },
          '25%': { 'clip-path': 'inset(40% 0 20% 0)' },
          '30%': { 'clip-path': 'inset(10% 0 60% 0)' },
          '35%': { 'clip-path': 'inset(15% 0 55% 0)' },
          '40%': { 'clip-path': 'inset(25% 0 35% 0)' },
          '45%': { 'clip-path': 'inset(30% 0 40% 0)' },
          '50%': { 'clip-path': 'inset(20% 0 50% 0)' },
          '55%': { 'clip-path': 'inset(10% 0 60% 0)' },
          '60%': { 'clip-path': 'inset(15% 0 55% 0)' },
          '65%': { 'clip-path': 'inset(25% 0 35% 0)' },
          '70%': { 'clip-path': 'inset(30% 0 40% 0)' },
          '75%': { 'clip-path': 'inset(40% 0 20% 0)' },
          '80%': { 'clip-path': 'inset(20% 0 50% 0)' },
          '85%': { 'clip-path': 'inset(10% 0 60% 0)' },
          '90%': { 'clip-path': 'inset(15% 0 55% 0)' },
          '95%': { 'clip-path': 'inset(25% 0 35% 0)' },
          '100%': { 'clip-path': 'inset(30% 0 40% 0)' },
        },
        glitchShift: {
          '0%':   { transform: 'translate(0, 0)' },
          '5%':   { transform: 'translate(6px, -3px)' },
          '10%':  { transform: 'translate(-8px, 5px)' },
          '15%':  { transform: 'translate(8px, 3px)' },
          '20%':  { transform: 'translate(-6px, -4px)' },
          '25%':  { transform: 'translate(10px, 5px)' },
          '30%':  { transform: 'translate(-10px, 3px)' },
          '35%':  { transform: 'translate(6px, -5px)' },
          '40%':  { transform: 'translate(-4px, 6px)' },
          '45%':  { transform: 'translate(8px, -3px)' },
          '50%':  { transform: 'translate(0, 0)' },
          '55%':  { transform: 'translate(-6px, 3px)' },
          '60%':  { transform: 'translate(8px, -5px)' },
          '65%':  { transform: 'translate(-8px, -3px)' },
          '70%':  { transform: 'translate(6px, 6px)' },
          '75%':  { transform: 'translate(-10px, 0)' },
          '80%':  { transform: 'translate(10px, -6px)' },
          '85%':  { transform: 'translate(-6px, 6px)' },
          '90%':  { transform: 'translate(4px, -3px)' },
          '95%':  { transform: 'translate(-4px, 3px)' },
          '100%': { transform: 'translate(0, 0)' },
        },
        glitchBlink: {
          '0%, 49%': { opacity: '0.55' },
          '50%, 100%': { opacity: '0.95' },
        },
      },
      animation: {
        'glitch-after': 'glitchShift var(--after-duration) steps(14) infinite, glitchBlink 0.22s steps(2) infinite',
        'glitch-before': 'glitchShift var(--before-duration) steps(17) infinite, glitchBlink 0.18s steps(2) infinite',
      },
    },
  },
  plugins: [],
}
