name: Disabled legacy deploy (use deploy-pages.yml)

on:
  # Solo manual, no se ejecuta en push
  workflow_dispatch: {}

jobs:
  disabled:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "This legacy workflow is disabled. Use .github/workflows/deploy-pages.yml"